[package]
name = "rnd_programs"
description = "Over and Over... nothing to see here -- just a bunch of programs being tested!"
version = "0.2.3"
authors = ["TheLazySol"]
edition = "2021"

[dependencies]